export default {
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_REQUEST: 'GET_ALL_USERS_REQUEST',
    GET_ALL_USERS_RESPONSE: 'GET_ALL_USERS_RESPONSE',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',

    GET_USER_BY_ID: 'GET_USER_BY_ID',
    GET_USER_BY_ID_REQUEST: 'GET_USER_BY_ID_REQUEST',
    GET_USER_BY_ID_RESPONSE: 'GET_USER_BY_ID_RESPONSE',
    GET_USER_BY_ID_ERROR: 'GET_USER_BY_ID_ERROR',
    
    CREATE_USER: 'CREATE_USER',
    CREATE_USER_REQUEST: 'CREATE_USER_REQUEST',
    CREATE_USER_RESPONSE: 'CREATE_USER_RESPONSE',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',

}

// we use it in REDUSERS, ACTION-CRTEATOR, SAGAS